answer=int(input("give a number less than 5 \n"))
print(answer<5)
print("--------------------------------------")
answer_2=input("give the capital of China\n")
print(answer_2=="beijing")
print("--------------------------------------")
answer_3=input("whats my favorite color\n")
print(answer_3=="blue")
print("---------------------------------------")
answer_4=input("what is mr osowski's full name\n")
print(answer_4=="Zachary Osowski")
print("--------------------------------------")
answer_5=input("are you real\n")
print(answer_5=="no")